### ISSUE TITLE
Gradle Scan publishing fails

### ISSUE THREAD

**Issue by 0neel** [cirruslabs/linux-image-templates#51]
Hey! We've just migrated from GitHub runners and almost everything worked out perfectly though there is an issue with Gradle Build Scan publishing.

We're using the official `gradle/actions/setup-gradle` action and it seems it has some issues with one of the internal requests.

The action configuration looks like this:
```yml
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"
        add-job-summary-as-pr-comment: on-failure
```

And the failure log looks like this:
```
Publishing build scan...

Publishing failed.

The response from https://scans-in.gradle.com/scans/publish/gradle/3.19.2/token was not from the build scan server.
Your network environment may be interfering, or the service may be unavailable.

If you believe this to be in error, please report this problem via https://gradle.com/help and include the following via copy/paste:

----------
Gradle version: 8.11.1
Plugin version: 3.19.2
Request URL: https://status.gradle.com/
Request ID: 2df62595-bc09-40b0-8af4-31862fe68568
Response status code: 400
Response content type: text/html
Response server type: AtlassianEdge
----------
```
